openapi: 3.0.0
info:
  title: Location API
  version: v1
paths:
  /locations:
    post:
      summary: Save a new location
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Location"
      responses:
        "200":
          description: Location saved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Location"
        "400":
          description: Invalid input
    get:
      summary: Get all locations
      responses:
        "200":
          description: A list of locations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Location"
  /locations/{reference}:
    get:
      summary: Find a location by reference
      parameters:
        - name: reference
          in: path
          required: true
          description: Reference ID of the location to retrieve
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Location found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Location"
        "404":
          description: Location not found
components:
  schemas:
    Location:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        reference:
          type: integer
          format: int64
        latitude:
          type: number
          format: double
          minimum: -90.0
          maximum: 90.0
        longitude:
          type: number
          format: double
          minimum: -180.0
          maximum: 180.0
      required:
        - reference
        - latitude
        - longitude
