openapi: 3.0.0
info:
  title: Location API
  version: v1
paths:
  /api/v1/persons:
    post:
      summary: Create a new person
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePersonRequest"
      responses:
        "201":
          description: Person created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreatePersonResponse"
        "400":
          description: Invalid input
    get:
      summary: Get persons by IDs
      parameters:
        - name: id
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: array
            items:
              type: integer
              format: int64
      responses:
        "200":
          description: A list of persons
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GetPersonResponse"
  /api/v1/persons/{id}/location:
    put:
      summary: Update a person's location
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateLocationRequest"
      responses:
        "200":
          description: Location updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LocationResponse"
        "400":
          description: Invalid input
        "404":
          description: Person not found
  /api/v1/persons/nearby:
    get:
      summary: Find nearby persons
      parameters:
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: double
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: double
        - name: radiusKm
          in: query
          required: true
          schema:
            type: number
            format: double
      responses:
        "200":
          description: A list of nearby persons
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/NearbyPersonResponse"
components:
  schemas:
    Location:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        reference:
          type: integer
          format: int64
        latitude:
          type: number
          format: double
          minimum: -90.0
          maximum: 90.0
        longitude:
          type: number
          format: double
          minimum: -180.0
          maximum: 180.0
      required:
        - reference
        - latitude
        - longitude
    CreatePersonRequest:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    CreatePersonResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - id
        - name
    GetPersonResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - id
        - name
    UpdateLocationRequest:
      type: object
      properties:
        latitude:
          type: number
          format: double
          minimum: -90.0
          maximum: 90.0
        longitude:
          type: number
          format: double
          minimum: -180.0
          maximum: 180.0
      required:
        - latitude
        - longitude
    LocationResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        personId:
          type: integer
          format: int64
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
      required:
        - id
        - personId
        - latitude
        - longitude
    NearbyPersonResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        distance:
          type: number
          format: double
      required:
        - id
        - name
        - distance
